name: CI
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Setup interactive ssh session
      if: ${{ failure() }}
      uses: Warpbuilds/gha-debug@v1